import Head from 'next/head'
import React from "react"
import Header from '@components/Header';
import Footer from '@components/Footer';
import Team from '@components/Team';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='main-wrapper'>
        home
        <Team/>
      </main>
      <Footer/>
    </>
  );
}
