import Head from 'next/head'
import HomeDesktop from "../components/HomeDesktop";
import React from "react"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeDesktop {...homeDesktopData} />
      </main>

      <footer></footer>
    </div>
  );
}


const projects1Data = {
  children: "Projects",
};

const projects2Data = {
  children: "Partners",
  className: "partners",
};

const buttonData = {
  icons:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/icons@2x.png",
  search: "Contact Us",
};

const navigationData = {
  iconsProfile:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/icons-profile-1@2x.png",
  projects1Props: projects1Data,
  projects2Props: projects2Data,
  buttonProps: buttonData,
};

const radioButtonData = {
  icon: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/--icon@2x.png",
  object:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/object@2x.png",
  states:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/--states@2x.png",
};

const button3Data = {
  icons:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/icons-2@2x.png",
  search: "Search",
};

const address1Data = {
  pin_Drop:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/pin-drop-1@2x.png",
};

const frame11Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed@2x.png",
  number: "5",
};

const frame12Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower@2x.png",
  number: "3",
  className: "frame-2",
};

const frame13Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car@2x.png",
  number: "3",
  className: "frame-3",
};

const frame51Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite@2x.png",
};

const frame41Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong@2x.png",
};

const footer1Data = {
  frame11Props: frame11Data,
  frame12Props: frame12Data,
  frame13Props: frame13Data,
  frame5Props: frame51Data,
  frame4Props: frame41Data,
};

const productCardVertical21Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/image-4@2x.png",
  x20000: "₹ 20-40 Lac",
  addressProps: address1Data,
  footerProps: footer1Data,
};

const address2Data = {
  pin_Drop:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/pin-drop-1@2x.png",
};

const frame14Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed@2x.png",
  number: "5",
};

const frame15Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower@2x.png",
  number: "3",
  className: "frame-2-1",
};

const frame16Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car@2x.png",
  number: "3",
  className: "frame-3-1",
};

const frame52Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite@2x.png",
};

const frame42Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong@2x.png",
};

const footer2Data = {
  frame11Props: frame14Data,
  frame12Props: frame15Data,
  frame13Props: frame16Data,
  frame5Props: frame52Data,
  frame4Props: frame42Data,
};

const productCardVertical22Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/image-6@2x.png",
  x20000: "₹ 25-30 Lac",
  className: "product-card-vertical-1",
  addressProps: address2Data,
  footerProps: footer2Data,
};

const address3Data = {
  pin_Drop:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/pin-drop-1@2x.png",
};

const frame17Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed@2x.png",
  number: "5",
};

const frame18Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower@2x.png",
  number: "3",
  className: "frame-2-2",
};

const frame19Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car@2x.png",
  number: "3",
  className: "frame-3-2",
};

const frame53Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite@2x.png",
};

const frame43Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong@2x.png",
};

const footer3Data = {
  frame11Props: frame17Data,
  frame12Props: frame18Data,
  frame13Props: frame19Data,
  frame5Props: frame53Data,
  frame4Props: frame43Data,
};

const productCardVertical23Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/image-7@2x.png",
  x20000: "₹ 2-3 Cr",
  className: "product-card-vertical-2",
  addressProps: address3Data,
  footerProps: footer3Data,
};

const frame22Data = {
  src: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/icons-8@2x.png",
};

const address4Data = {
  pin_Drop:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/pin-drop-1@2x.png",
};

const dividerData = {
  surname: "White Forest",
  addressProps: address4Data,
};

const frame110Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed@2x.png",
  number: "5",
};

const frame111Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/--states@2x.png",
  number: "3",
  className: "frame-3-3",
};

const frame54Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/--states@2x.png",
};

const frame44Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/--states@2x.png",
};

const productCardVertical3Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/image-5@2x.png",
  shower:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower-4@2x.png",
  number: "3",
  dividerProps: dividerData,
  frame11Props: frame110Data,
  frame12Props: frame111Data,
  frame5Props: frame54Data,
  frame4Props: frame44Data,
};

const frame9362Data = {
  className: "frame-937",
};

const frame112Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed-7@2x.png",
  number: "5",
  className: "frame-1-3",
};

const frame113Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower-7@2x.png",
  number: "3",
  className: "frame-2-3",
};

const frame114Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car-7@2x.png",
  number: "3",
  className: "frame-3-4",
};

const frame55Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite-7@2x.png",
  className: "frame-5-1",
};

const frame45Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong-7@2x.png",
  className: "frame-4-1",
};

const productCardHorizontal1Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-2@2x.png",
  frame11Props: frame112Data,
  frame12Props: frame113Data,
  frame13Props: frame114Data,
  frame5Props: frame55Data,
  frame4Props: frame45Data,
};

const frame115Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed-7@2x.png",
  number: "5",
  className: "frame-1-4",
};

const frame116Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower-7@2x.png",
  number: "3",
  className: "frame-2-4",
};

const frame117Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car-7@2x.png",
  number: "3",
  className: "frame-3-5",
};

const frame56Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite-7@2x.png",
  className: "frame-5-2",
};

const frame46Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong-7@2x.png",
  className: "frame-4-2",
};

const productCardHorizontal2Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-2-1@2x.png",
  className: "product-card-horizontal-1",
  frame11Props: frame115Data,
  frame12Props: frame116Data,
  frame13Props: frame117Data,
  frame5Props: frame56Data,
  frame4Props: frame46Data,
};

const frame118Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed-7@2x.png",
  number: "5",
  className: "frame-1-5",
};

const frame119Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower-7@2x.png",
  number: "3",
  className: "frame-2-5",
};

const frame120Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car-7@2x.png",
  number: "3",
  className: "frame-3-6",
};

const frame57Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite-7@2x.png",
  className: "frame-5-3",
};

const frame47Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong-7@2x.png",
  className: "frame-4-3",
};

const productCardHorizontal3Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-2-2@2x.png",
  className: "product-card-horizontal-2",
  frame11Props: frame118Data,
  frame12Props: frame119Data,
  frame13Props: frame120Data,
  frame5Props: frame57Data,
  frame4Props: frame47Data,
};

const frame121Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/bed-7@2x.png",
  number: "5",
  className: "frame-1-6",
};

const frame122Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/shower-7@2x.png",
  number: "3",
  className: "frame-2-6",
};

const frame123Data = {
  bed: "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/directions-car-7@2x.png",
  number: "3",
  className: "frame-3-7",
};

const frame58Data = {
  favorite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/favorite-7@2x.png",
  className: "frame-5-4",
};

const frame48Data = {
  center_Focus_Strong:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/center-focus-strong-7@2x.png",
  className: "frame-4-4",
};

const productCardHorizontal4Data = {
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-2-3@2x.png",
  className: "product-card-horizontal-3",
  frame11Props: frame121Data,
  frame12Props: frame122Data,
  frame13Props: frame123Data,
  frame5Props: frame58Data,
  frame4Props: frame48Data,
};

const button5Data = {
  children: "See More",
};

const homeDesktopData = {
  findYourDreamHome: (
    <React.Fragment>
      Find Your
      <br />
      Dream Home
    </React.Fragment>
  ),
  exploreNewApartmen:
    "Explore new apartments, land estates, house and land, home designs, builders and more.",
  image:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/image-3@1x.png",
  polygon1:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/polygon-1@1x.png",
  howSqfthomeCanHelp: "How Sqfthome can help",
  sqfthomeProvidesAnAwesomeSolution: "Sqfthome provides an awesome solution!",
  buyAHome: "Buy a home",
  withOver1Million1:
    "With over 1 million+ homes for sale available on the website, Sqfthome can match you with a house you will want to call home.",
  rentAHome: "Rent a home",
  withOver1Million2:
    "With over 1 million+ homes for sale available on the website, Sqfthome can match you with a house you will want to call home.",
  polygon2:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/polygon-2@1x.png",
  buy: "Buy",
  radioButton:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/radio-button@2x.png",
  rent: "Rent",
  navigation1:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/navigation-1@2x.png",
  searchByLocation: "Search by location, landmark, builder, or project",
  dropdown:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/dropdown@2x.png",
  residential: "Residential",
  weProvideBuyAndS: "We Provide Buy and Sell Property with Trusted Developers",
  loremIpsumDolorSi:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non tristique bibendum tellus ut arcu. Lacus lorem turpis sed felis urna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non tristique bibendum tellus ut arcu. Lacus lorem turpis sed felis urna.",
  abstractLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/abstract--logo---white-@2x.png",
  beazerHomesLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/beazer-homes--logo---white-@2x.png",
  hippoLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/hippo--logo---white-@2x.png",
  airbnbLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/airbnb--logo---white-@2x.png",
  pultegroupLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/pultegroup--logo---white-@2x.png",
  anchorLogoWhite:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/anchor--logo---white-@2x.png",
  polygon4:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/polygon-4@2x.png",
  polygon3:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/polygon-3@2x.png",
  homesForSaleNearYou: "Homes for Sale Near you",
  checkOutSomeOfOurLatestProperties: "Check out some of our latest properties",
  houseforsaleConverted1:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/houseforsale--converted--1@2x.png",
  weAreCommittedTo:
    "We are committed to making our clients happy with our services",
  whatPeopleSay: "What people say",
  format_Quote:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/format-quote@2x.png",
  newlyAddedResaleProperty: "Newly added Resale property",
  findTheHotSpotResaleProperties: "Find the hot spot resale properties",
  frame1005:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-1146@1x.png",
  ourTeam: "Our Team",
  maskGroup1:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/mask-group@2x.png",
  maskGroup2:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/mask-group-1@2x.png",
  spanText1: (
    <React.Fragment>
      Vicky Taneja
      <br />
    </React.Fragment>
  ),
  spanText2: "Co-Founder",
  spanText3: (
    <React.Fragment>
      Amit Lal
      <br />
    </React.Fragment>
  ),
  spanText4: "Co-Founder",
  loremIpsumDolorS:
    "“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus. Vitae morbi ac proin blandit nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus. “Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus. Vitae morbi ac proin blandit nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus. “Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus. Vitae morbi ac proin blandit nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Gravida pharetra felis elit id erat phasellus.",
  logo1:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/logo-1-1@2x.png",
  product: "Product",
  homeAboutProjectsContact: (
    <React.Fragment>
      Home
      <br />
      About
      <br />
      Projects
      <br />
      Contact
    </React.Fragment>
  ),
  rectangle1145:
    "https://anima-uploads.s3.amazonaws.com/projects/62af2dcdf1e6f9b16eaa21a7/releases/62af2eddce1cf6ae325f421a/img/rectangle-1145@1x.png",
  navigationProps: navigationData,
  radioButtonProps: radioButtonData,
  button3Props: button3Data,
  productCardVertical21Props: productCardVertical21Data,
  productCardVertical22Props: productCardVertical22Data,
  productCardVertical23Props: productCardVertical23Data,
  frame22Props: frame22Data,
  productCardVertical3Props: productCardVertical3Data,
  frame936Props: frame9362Data,
  productCardHorizontal1Props: productCardHorizontal1Data,
  productCardHorizontal2Props: productCardHorizontal2Data,
  productCardHorizontal3Props: productCardHorizontal3Data,
  productCardHorizontal4Props: productCardHorizontal4Data,
  button5Props: button5Data,
};



